- name: "Run common"
  ansible.builtin.import_playbook: common.yml

- name: "Run zsh"
  ansible.builtin.import_playbook: zsh.yml

- name: "Run node"
  ansible.builtin.import_playbook: node.yml

- name: "Run neovim"
  ansible.builtin.import_playbook: neovim.yml

- name: "Install golang"
  hosts: localhost
  roles:
    - role: gantsign.golang
      golang_gopath: "$HOME/workspace-go"
