- name: Install nvm and node lts
  hosts: "localhost"
  tasks:
    - name: Install nvm and lts node
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          source {{ ansible_env.HOME }}/.nvm/nvm.sh
          nvm install --lts
          corepack enable
        executable: /bin/zsh
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install pnpm
      ansible.builtin.shell:
        cmd: |
          source {{ ansible_env.HOME }}/.nvm/nvm.sh
          if ! command -v pnpm &> /dev/null
          then
            npm install -g pnpm
          fi
        executable: /bin/zsh
      register: pnpm_installed
      changed_when: pnpm_installed is search("added 1 package in")

    - name: Install pnpm tab completion
      ansible.builtin.shell:
        cmd: |
          source {{ ansible_env.HOME }}/.nvm/nvm.sh
          pnpm install-completion zsh
        executable: /bin/zsh
      register: pnpm_completion_installed
      changed_when: pnpm_completion_installed is search("Make sure to reload your")
      ignore_errors: true

    - name: Install global npm packages
      ansible.builtin.shell:
        cmd: |
          source {{ ansible_env.HOME }}/.nvm/nvm.sh
          npm install -g "{{ item }}"
        executable: /bin/zsh
      loop:
        - tldr
        - knip
      changed_when: false
