- name: Print all available facts
  hosts: "localhost"
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts.{{ item }}
      with_items:
        - distribution
        - distribution_file_parsed
        - distribution_file_path
        - distribution_file_variety
        - distribution_major_version
        - distribution_release
        - distribution_version
        - os_family
