- name: "Update apt"
  hosts: "localhost"
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        upgrade: "yes"

    - name: Install packages
      apt: name={{item}}
      with_items:
        - git
        - python3-pip
        - bat
        - btop
        - nmap
        - fzf
        - stow
